baseURL = 'https://kai1805.github.io/'
languageCode = 'en-us'
title = "Kai's Blog"
theme = 'hugo-book'


[params]
  BookTheme = 'auto'
  BookToC = true
  BookSection = 'docs'
  BookRepo = 'https://github.com/kai1805/blog'
  BookEditPath = 'edit/main/content'

